"""Launch QGIS with the debug bridge already listening.

Mechanism: ``qgis --code <bootstrap.py>`` runs a small script inside the
freshly started QGIS, after QGIS has finished initializing (plugins
loaded, main window up) - confirmed by running this for real against a
QGIS 3.44.5 installation, not just assumed. The script starts a debugpy
listener and writes a *ready file*; this module polls that file. The
debug port itself is never probed, so debugpy's own socket is never
touched from outside.

The same ``sys.executable``-is-the-QGIS-binary problem that
``qgis_plugin/debug_bridge.py`` works around applies here too: the
bootstrap passes the venv's/QGIS's own python to
``debugpy.configure(python=...)`` before calling ``listen()``, or
``debugpy.listen()`` fails after ~20-30s with "timed out waiting for
adapter to connect" - reproduced for real in this repo's history before
the fix (see CHANGELOG 0.2.2 and the plugin bridge's docstring).

Everything else here is testable without QGIS (Popen and the filesystem
are injectable). Not covered by the tests: the behaviour of a real QGIS
binary and its exact ``--code`` timing on every OS/version — see
docs/*/usage.md's "Verified vs. not verified" section.
"""
from __future__ import annotations

import os
import platform
import shutil
import subprocess
import tempfile
import time
import uuid
from pathlib import Path
from typing import Callable, Mapping, Sequence

from .detectors.base import QgisInstallation
from .i18n_util import t

BOOTSTRAP_SOURCE = '''\
"""Generated by devbridge. Runs inside QGIS (qgis --code)."""
import os
import pathlib

_host = os.environ.get("DEVBRIDGE_HOST", "localhost")
_port = int(os.environ.get("DEVBRIDGE_PORT", "5678"))
_wait = os.environ.get("DEVBRIDGE_WAIT_FOR_CLIENT") == "1"
_python = os.environ.get("DEVBRIDGE_PYTHON")
_ready = os.environ.get("DEVBRIDGE_READY_FILE")


def _report(message):
    if _ready:
        pathlib.Path(_ready).write_text(message, encoding="utf-8")


try:
    import debugpy

    # sys.executable is the QGIS binary in an embedded interpreter; without
    # this, debugpy would spawn its adapter through it (a second QGIS) and
    # listen() would fail ~20-30s later - confirmed against a real QGIS.
    if _python:
        debugpy.configure(python=_python)
    debugpy.listen((_host, _port))
    _report("ok")
    if _wait:
        debugpy.wait_for_client()
except Exception as exc:  # reported to the launcher, never raised into QGIS
    _report("error: %s" % exc)
'''


def find_qgis_executable(qgis: QgisInstallation, system: str | None = None) -> Path | None:
    system = system or platform.system()
    if system == "Windows":
        root = qgis.root
        flavour = qgis.qgis_python_dir.parent.name if qgis.qgis_python_dir else "qgis"
        candidates = [
            root / "bin" / f"{flavour}.bat",          # OSGeo4W wrappers set up the environment
            root / "bin" / f"{flavour}-bin.exe",
            root / "apps" / flavour / "bin" / "qgis-bin.exe",
            root / "bin" / "qgis-bin.exe",             # standalone installer layout (verified)
            root / "bin" / "qgis-ltr-bin.exe",
        ]
        for candidate in candidates:
            if candidate.is_file():
                return candidate
        return None

    if system == "Darwin":
        binary = qgis.root / "MacOS" / "QGIS"      # root is <app>/Contents
        return binary if binary.is_file() else None

    found = shutil.which("qgis")
    if found:
        return Path(found)
    fallback = Path("/usr/bin/qgis")
    return fallback if fallback.is_file() else None


def real_python_for(qgis: QgisInstallation) -> str | None:
    """The interpreter debugpy should use for its adapter, or None when the
    detected one is a wrapper (.bat) that cannot be passed to debugpy."""
    exe = qgis.python_exe
    if exe.name.lower().startswith("python") and exe.suffix.lower() != ".bat":
        return str(exe)
    return None


def write_bootstrap(directory: Path) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "devbridge_qgis_bootstrap.py"
    path.write_text(BOOTSTRAP_SOURCE, encoding="utf-8")
    return path


def build_launch_env(*, host: str, port: int, wait_for_client: bool,
                     ready_file: Path, python_exe: str | None) -> dict[str, str]:
    env = {
        "DEVBRIDGE_HOST": host,
        "DEVBRIDGE_PORT": str(port),
        "DEVBRIDGE_WAIT_FOR_CLIENT": "1" if wait_for_client else "0",
        "DEVBRIDGE_READY_FILE": str(ready_file),
    }
    if python_exe:
        env["DEVBRIDGE_PYTHON"] = python_exe
    return env


def build_launch_command(exe: Path, bootstrap: Path, project_file: str | None = None,
                         extra_args: Sequence[str] = ()) -> list[str]:
    cmd = [str(exe), "--code", str(bootstrap), *extra_args]
    if project_file:
        cmd.append(project_file)
    return cmd


def wait_for_ready(ready_file: Path, timeout: float, poll: float = 0.25,
                   process=None, sleep: Callable[[float], None] = time.sleep,
                   clock: Callable[[], float] = time.monotonic) -> tuple[bool, str]:
    """Returns (ok, detail). detail is 'ok', an error text, 'timeout' or
    'exited:<code>'.

    A non-zero exit is treated as a real failure (the executable could not
    even start) and reported immediately. Exit code 0 is NOT - confirmed
    against a real OSGeo4W install: its qgis*.bat wrappers set up the
    environment, `start /B` the actual qgis*-bin.exe as a detached
    grandchild, and return 0 right away, while the real QGIS keeps loading
    for another 20-40s. Bailing out on that exit would report a launch
    that is still succeeding in the background as a failure."""
    def _read() -> str | None:
        try:
            text = ready_file.read_text(encoding="utf-8").strip()
        except OSError:
            return None
        return text or None

    deadline = clock() + timeout
    while True:
        content = _read()
        if content is not None:
            return (content == "ok", content)
        if process is not None:
            code = process.poll()
            if code is not None and code != 0:
                content = _read()            # it may have been written just before exit
                if content is not None:
                    return (content == "ok", content)
                return (False, f"exited:{code}")
        if clock() >= deadline:
            return (False, "timeout")
        sleep(poll)


def _spawn_detached(cmd: list[str], env: Mapping[str, str], popen=subprocess.Popen):
    kwargs: dict = dict(env=dict(env), stdin=subprocess.DEVNULL,
                        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if os.name == "nt":
        kwargs["creationflags"] = (getattr(subprocess, "DETACHED_PROCESS", 0x00000008)
                                   | getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0x00000200))
    else:
        kwargs["start_new_session"] = True
    return popen(cmd, **kwargs)


def launch_qgis(qgis: QgisInstallation, *, host: str = "localhost", port: int = 5678,
                wait_for_client: bool = False, wait_ready: bool = False,
                timeout: float = 60.0, project_file: str | None = None,
                extra_args: Sequence[str] = (), verbose_print=print,
                popen=subprocess.Popen, work_dir: Path | None = None,
                system: str | None = None) -> int:
    exe = find_qgis_executable(qgis, system=system)
    if exe is None:
        verbose_print(t("qgis_exe_not_found"))
        return 1

    python_exe = real_python_for(qgis)
    if python_exe is None:
        verbose_print(t("launch_no_python_warning"))

    work_dir = work_dir or Path(tempfile.gettempdir()) / "devbridge"
    bootstrap = write_bootstrap(work_dir)
    ready_file = work_dir / f"ready-{uuid.uuid4().hex}.txt"

    env = {**os.environ, **build_launch_env(
        host=host, port=port, wait_for_client=wait_for_client,
        ready_file=ready_file, python_exe=python_exe)}
    cmd = build_launch_command(exe, bootstrap, project_file, extra_args)

    verbose_print(t("launching_qgis", exe=exe))
    try:
        process = _spawn_detached(cmd, env, popen=popen)
    except OSError as exc:
        verbose_print(t("launch_failed", detail=exc))
        return 1

    if not wait_ready:
        return 0

    verbose_print(t("waiting_ready", host=host, port=port, timeout=int(timeout)))
    ok, detail = wait_for_ready(ready_file, timeout, process=process)
    try:
        ready_file.unlink()
    except OSError:
        pass
    if ok:
        verbose_print(t("ready_ok", host=host, port=port))
        return 0
    if detail == "timeout":
        verbose_print(t("ready_timeout", timeout=int(timeout)))
    else:
        verbose_print(t("ready_error", detail=detail))
    return 1
